### ISSUE TITLE
no implicit conversion of Hash into String 

### ISSUE THREAD

**Issue by shawngraham** [thepeergroup/aspen#38]
Hi, just trying this out, following the quick start. Getting this error on `aspen build` using the demo data:

undefined method `close' for nil:NilClass (NoMethodError)

no implicit conversion of Hash into String(TypeError)

```bash
/Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/lib/aspen/conversion.rb:32:in `ensure in to_aspen': undefined method `close' for nil:NilClass (NoMethodError)
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/lib/aspen/conversion.rb:32:in `to_aspen'
	from bin/convert:14:in `<main>'
/Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1421:in `initialize': no implicit conversion of Hash into String (TypeError)
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1421:in `open'
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/3.0.0/csv.rb:1421:in `open'
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/lib/aspen/conversion.rb:28:in `to_aspen'
	from bin/convert:14:in `<main>'
/Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/lib/aspen/cli/commands/build_steps.rb:105:in `call': `bin/convert` didn't work, stopping build. See above Traceback. (RuntimeError)
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/lib/aspen/cli/commands/build.rb:18:in `call'
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:114:in `perform_registry'
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:67:in `call'
	from /Users/shawngraham/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/aspen-cli-0.1.2/bin/aspen:3:in `<top (required)>'
	from /Users/shawngraham/.rbenv/versions/3.0.3/bin/aspen:25:in `load'
	from /Users/shawngraham/.rbenv/versions/3.0.3/bin/aspen:25:in `<main>'
```

Thanks!

**Comment by shawngraham** [comment]
ok, so if I use rbenv to switch ruby from 3.0.3 to 2.9.1, then I no longer get this error.
